/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './pages/__root'
import { Route as AdminImport } from './pages/admin'
import { Route as DurianIndexImport } from './pages/durian/index'
import { Route as AdminIndexImport } from './pages/admin/index'
import { Route as DurianRegisterImport } from './pages/durian/register'
import { Route as DurianProfileImport } from './pages/durian/profile'
import { Route as DurianProductsImport } from './pages/durian/products'
import { Route as DurianLoginImport } from './pages/durian/login'
import { Route as DurianCheckoutImport } from './pages/durian/checkout'
import { Route as DurianCartImport } from './pages/durian/cart'
import { Route as DurianAboutImport } from './pages/durian/about'
import { Route as AdminSettingsImport } from './pages/admin/settings'
import { Route as AdminPromoCodesImport } from './pages/admin/promo-codes'
import { Route as AdminProductsImport } from './pages/admin/products'
import { Route as AdminOrdersImport } from './pages/admin/orders'
import { Route as AdminBannersImport } from './pages/admin/banners'

// Create/Update Routes

const AdminRoute = AdminImport.update({
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const DurianIndexRoute = DurianIndexImport.update({
  path: '/durian/',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)

const DurianRegisterRoute = DurianRegisterImport.update({
  path: '/durian/register',
  getParentRoute: () => rootRoute,
} as any)

const DurianProfileRoute = DurianProfileImport.update({
  path: '/durian/profile',
  getParentRoute: () => rootRoute,
} as any)

const DurianProductsRoute = DurianProductsImport.update({
  path: '/durian/products',
  getParentRoute: () => rootRoute,
} as any)

const DurianLoginRoute = DurianLoginImport.update({
  path: '/durian/login',
  getParentRoute: () => rootRoute,
} as any)

const DurianCheckoutRoute = DurianCheckoutImport.update({
  path: '/durian/checkout',
  getParentRoute: () => rootRoute,
} as any)

const DurianCartRoute = DurianCartImport.update({
  path: '/durian/cart',
  getParentRoute: () => rootRoute,
} as any)

const DurianAboutRoute = DurianAboutImport.update({
  path: '/durian/about',
  getParentRoute: () => rootRoute,
} as any)

const AdminSettingsRoute = AdminSettingsImport.update({
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)

const AdminPromoCodesRoute = AdminPromoCodesImport.update({
  path: '/promo-codes',
  getParentRoute: () => AdminRoute,
} as any)

const AdminProductsRoute = AdminProductsImport.update({
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)

const AdminOrdersRoute = AdminOrdersImport.update({
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)

const AdminBannersRoute = AdminBannersImport.update({
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/admin/banners': {
      preLoaderRoute: typeof AdminBannersImport
      parentRoute: typeof AdminImport
    }
    '/admin/orders': {
      preLoaderRoute: typeof AdminOrdersImport
      parentRoute: typeof AdminImport
    }
    '/admin/products': {
      preLoaderRoute: typeof AdminProductsImport
      parentRoute: typeof AdminImport
    }
    '/admin/promo-codes': {
      preLoaderRoute: typeof AdminPromoCodesImport
      parentRoute: typeof AdminImport
    }
    '/admin/settings': {
      preLoaderRoute: typeof AdminSettingsImport
      parentRoute: typeof AdminImport
    }
    '/durian/about': {
      preLoaderRoute: typeof DurianAboutImport
      parentRoute: typeof rootRoute
    }
    '/durian/cart': {
      preLoaderRoute: typeof DurianCartImport
      parentRoute: typeof rootRoute
    }
    '/durian/checkout': {
      preLoaderRoute: typeof DurianCheckoutImport
      parentRoute: typeof rootRoute
    }
    '/durian/login': {
      preLoaderRoute: typeof DurianLoginImport
      parentRoute: typeof rootRoute
    }
    '/durian/products': {
      preLoaderRoute: typeof DurianProductsImport
      parentRoute: typeof rootRoute
    }
    '/durian/profile': {
      preLoaderRoute: typeof DurianProfileImport
      parentRoute: typeof rootRoute
    }
    '/durian/register': {
      preLoaderRoute: typeof DurianRegisterImport
      parentRoute: typeof rootRoute
    }
    '/admin/': {
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminImport
    }
    '/durian/': {
      preLoaderRoute: typeof DurianIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AdminRoute.addChildren([
    AdminBannersRoute,
    AdminOrdersRoute,
    AdminProductsRoute,
    AdminPromoCodesRoute,
    AdminSettingsRoute,
    AdminIndexRoute,
  ]),
  DurianAboutRoute,
  DurianCartRoute,
  DurianCheckoutRoute,
  DurianLoginRoute,
  DurianProductsRoute,
  DurianProfileRoute,
  DurianRegisterRoute,
  DurianIndexRoute,
])

/* prettier-ignore-end */
